{% set version = "5.7.1" %}

package:
  name: zsh
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/zsh/files/zsh/{{ version }}/zsh-{{ version }}.tar.xz/download
  fn: zsh-{{ version }}.tar.xz
  sha256: 7260292c2c1d483b2d50febfa5055176bd512b32a8833b116177bf5f01e77ee8
  patches:
    # Skip a test that fails on CI, some filesystem weirdness
    - skip-N-cond-test.patch

build:
  number: 0
  skip: true  # [win]
  script: |
    ./configure --prefix="$PREFIX" --with-tcsetpgrp --enable-pcre
    make
    make check
    make install

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ncurses
    - pcre
  run:
    - ncurses

test:
  commands:
    - zsh --version
    - zsh -c 'echo hi'

about:
  home: http://www.zsh.org
  license: Custom
  license_family: MIT
  license_file: LICENCE
  summary: Zsh is a shell designed for interactive use, although it is also a powerful scripting language.
  doc_url: http://zsh.sourceforge.net/Doc/Release/zsh_toc.html
  dev_url: https://sourceforge.net/p/zsh/code/ci/master/tree/

extra:
  recipe-maintainers:
    - djsutherland
